---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v5.0.0"
    hooks:
      - id: fix-byte-order-marker
      - id: check-json
      - id: pretty-format-json
        args: [--autofix, --indent=2]
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: [--fix=auto]
      - id: trailing-whitespace
      - id: check-added-large-files
        args: [--maxkb=1024]
  # Run the Ruff linter.
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.7.1
    hooks:
      - id: ruff
  # Run the Ruff formatter.
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.7.1
    hooks:
      - id: ruff-format
